sections_to_scrape = [
  'Camas supletorias',
  'Camas infantiles',
  'Camas juveniles',
  'Camas dobles',
  'Camas literas',
  'Camas nido',
  'Camas de matrimonio',
  'Camas individuales',
  'Base tapizadas',
  'Somieres',
  'Canapés',
  'Dormitorios matrimonio',
  'Dormitorios juveniles',
  'Cajones',
  'Cabeceros',
  'Mesas de salón',
  'Expositores',
  'Librerías',
  'Muebles de TV',
  'Estanterías',
  'Conjunto de mesas y sillas de comedor',
  'Colecciones de salón',
  'Mesas de escritorio',
  'Cajoneras de oficinas',
  'Accesorios de oficina',
  'Escritorios',
  'Sillas de escritorio',
  'Estanterías',
  'Consolas',
  'Cómodas',
  'Tocadores',
  'Aparadores',
  'Sinfonier',
  'Librerías',
  'Bufete',
  'Mesitas de noche',
  'Armarios',
  'Recibidores',
  'Vitrinas',
  'Cajoneras',
  'Zapateros',
  'Armarios de matrimonio',
  'Mesas',
  'Estanterías de habitación',
  'Sinfoniers',
  'Cabeceros de matrimonio',
  'Cómodas',
  'Mesitas de noche',
  'Escritorio oficina',
  'Escritorio gaming',
  'Escritorio ordenador',
  'Escritorio infantil',
  'Escritorio juvenil',
  'Mesas multiusos',
  'Conjuntos de mesas y sillas',
  'Mesas altas',
  'Cajoneras juvenil e infantil',
  'Escritorios juvenil e infantil',
  'Armarios juvenil e infantil',
  'Mesitas de noche juvenil e infantil',
  'Mesas gaming',
  'Sillas Gaming',
  'Mesas de cocina',
  'Sillas de cocina',
  'Armarios de cocina',
  'Conjuntos de mesas y sillas de cocina',
  'Muebles auxiliares de cocina',
  'Sillas de comedor',
  'Muebles para habitación de bebé',
  'Cunas',
  'Cama bebé',
  'Botiquines',
  'Conjuntos de muebles para baño',
  'Tocadores para baño',
  'Armarios para baño',
  'Repisa para baño',
  'Lavabos'
]

specs_headers = {
  'width': [
    'Ancho'
  ],
  'depth': [
    'Fondo'
  ],
  'height': [
    'Alto'
  ],
  'color': [
  ],
  'material': [
    'Material'
  ],
  'finish': [
    'Acabado'
  ]
}
