sections_to_scrape = [
  "Meubles de gaming",
  "Meubles TV",
  "Bibliothèques et étagères",
  "Rangements bureau et salon",
  "Buffets et consoles",
  "Tables et bureaux",
  "Chaises",
  "Tables et chaises de bar",
  "Mobilier de café et restaurant",
  "Dessertes et îlots",
  "Lits",
  "Armoires, penderies et dressings",
  "Commodes et caissons à tiroirs",
  "Séparateurs de pièce",
  "Meubles enfant",
  "Meubles bébé",
  "Meubles de salle à manger",
  "Solutions de rangement",
  "Armoires, penderies et dressings",
  "Commodes et caissons à tiroirs",
  "Meubles TV",
  "Buffets et consoles",
  "Bibliothèques et étagères",
  "Rangements chaussures et portemanteaux",
  "Rangements bureau et salon",
  "Dessertes et îlots",
  "Étagères murales",
  "Rangements enfant",
  "Chaises de bureau",
  "Bureaux et support PC/tablettes",
  "Ensembles chaise et bureau",
  "Tables multifonctionnelles",
  "Caissons à tiroirs",
  "Meubles de rangement bureau",
  "Solutions cuisine équipée",
  "Dessertes et îlots cuisine",
  "Boutons et poignées cuisine",
  "Portes et façades de tiroirs",
  "Meubles de cuisine",
  "Meubles sous vasques/lavabos",
  "Rangements salle de bain",
  "Miroirs salle de bain",
  "Ensemble meubles de salle de bain",
  "Vasques et lavabos",
  "Buanderie et accessoires"
]

specs_headers = {
  'width': [
    'Largeur',
    'Larg. couchage',
  ],
  'depth': [
    'Profondeur',
    'Longueur',
    'Long. couchage',
  ],
  'height': [
    'Hauteur',
    'Hauteur max.',
    'Hauteur totale',
  ]
}
