sections_to_scrape = [
  ['Salle à Manger', 'Tables à Manger'],
  ['Salle à Manger', 'Chaises'],
  ['Salle à Manger', 'Tables Hautes'],
  ['Salle à Manger', 'Buffets et Commodes'],
  ['Salle à Manger', 'Vitrines et Bibliothèques'],
  ['Salle à Manger', 'Etagères Murales'],
  ['Salle à Manger', 'Consoles'],
  ['Salon', 'Meuble tv mural'],
  ['Salon', 'Buffet'],
  ['Salon', "Table d'appoint"],
  ['Salon', 'Meuble tv'],
  ['Salon', 'Console'],
  ['Salon', 'Chaise'],
  ['Salon', 'Table Basse'],
  ['Chambre à Coucher', 'Lits'],
  ['Chambre à Coucher', 'Sommiers'],
  ['Chambre à Coucher', 'Chevet'],
  ['Chambre à Coucher', 'Armoires'],
  ['Chambre à Coucher', 'Commodes et Coiffeuses'],
  ['Chambre à Coucher', 'Bar à Beauté'],
  ['Chambre à Coucher', 'Etagères Murales'],
  ['Chambre Enfant', 'Lits'],
  ['Chambre Enfant', 'Chevets'],
  ['Chambre Enfant', 'Bureaux'],
  ['Chambre Enfant', 'Bureaux Gamer'],
  ['Chambre Enfant', 'Chaises et Fauteuils de Bureau'],
  ['Chambre Enfant', 'Chaises Gamer'],
  ['Chambre Enfant', 'Commodes'],
  ['Chambre Enfant', 'Armoires'],
  ['Chambre Enfant', 'Bibliothèques'],
  ['Chambre Enfant', 'Tiroirs lit'],
  ['Chambre Bébé', 'Lits Bébés'],
  ['Chambre Bébé', 'Tables à langer et Commodes'],
  ['Chambre Bébé', 'Armoires'],
  ['Rangement', 'Armoires'],
  ['Rangement', 'Chevets'],
  ['Rangement', 'Meubles à chaussures'],
  ['Rangement', 'Commodes'],
  ['Rangement', 'Meubles Multifonctions'],
  ['Rangement', 'Etagères et Bibliothèques'],
  ['Rangement', 'Etagères Murales'],
  ['Rangement', 'Vestiaires'],
  ['Rangement', 'Salle de bain'],
  ['Mobilier Pro', 'Bureaux de Direction'],
  ['Mobilier Pro', 'Bureaux Opérationnels'],
  ['Mobilier Pro', 'Bureaux Multimédia'],
  ['Mobilier Pro', 'Tables de Réunion'],
  ['Mobilier Pro', 'Fauteuils de Direction'],
  ['Mobilier Pro', 'Fauteuils et Sièges Opérateurs'],
  ['Mobilier Pro', 'Fauteuils Sénateurs'],
  ['Mobilier Pro', 'Fauteuils Visiteurs'],
  ['Mobilier Pro', 'Armoire de bureau'],
  ['Mobilier Pro', 'Caisson mobile '],
  ['Mobilier Pro', 'Etagère de bureau'],
  ['Mobilier Pro', "Tables basses d'accueil"]
]

specs_classes = {
  'width': 'attribute_value_longueur_cm',
  'depth': 'attribute_value_largeur_profondeur_cm',
  'height': 'attribute_value_hauteur_cm',
  'color': 'attribute_value_coloris',
  'material': 'attribute_value_matiere_structure',
  'finish': 'attribute_value_matiere_revetement',
}

