sections_to_scrape = [
  'Armoires à linge',
  'Armoires à portes battantes',
  'Armoires à portes coulissantes',
  "Armoires à linge d'enfant",
  'Dressings',
  'Dressoirs',
  'Bibliothèques',
  'Meubles tv',
  'Armoires murales',
  'Commodes',
  'Buffets',
  'Armoire à chaussures',
  'Tables de nuit',
  'Ensembles de salle de bains',
  'Meubles sous-lavabo',
  'Armoires hautes',
  'Tables de salle à manger rondes',
  'Tables de salle à manger en bois',
  'Tables de salle à manger aspect industriel',
  'Tables de salle à manger rectangulaires',
  'Tables de salon',
  'Bureaux',
  "Bureaux d'angle",
  'Chaises de bureau',
  'Lits 1 personne',
  'Lits une place et demie',
  'Lits 2 personnes',
  "Lits d'enfant",
  'Coiffeuses'
]
