sections_to_scrape = [
  ['Salas de Jantar', 'Aparadores'],
  ['Salas de Jantar', 'Cadeiras de sala'],
  ['Salas de Jantar', 'Mesas de jantar'],
  ['Salas de Jantar', 'Vitrines'],
  ['Salas de Estar', 'Mesas de centro'],
  ['Salas de Estar', 'Consolas'],
  ['Salas de Estar', 'Móveis de TV'],
  ['Salas de Estar', 'Estantes de sala'],
  ['Quartos', 'Beliches'],
  ['Quartos', 'Camas'],
  ['Quartos', 'Camiseiros'],
  ['Quartos', 'Cómodas'],
  ['Quartos', 'Mesas de cabeceira'],
  ['Quartos', 'Quartos de casal'],
  ['Quartos', 'Quartos juvenis'],
  ['Quartos', 'Roupeiros'],
  ['Escritório', 'Cadeiras de Escritório'],
  ['Escritório', 'Estantes de escritório'],
  ['Escritório', 'Secretárias'],
  ['Escritório', 'Armários de escritório'],
  ['Escritório', 'Blocos de gavetas'],
  ['Arrumação e <br>Pequeno móvel', 'Consolas'],
  ['Arrumação e <br>Pequeno móvel', 'Roupeiros'],
  ['Arrumação e <br>Pequeno móvel', 'Sapateiras'],
  ['Mobiliário de Cozinha', None],
]
